sudo: true
language: python

env:
  - SHELL_PATH=build-roboto.sh

before_script: 
  - pip install fontmake

  - pip install --upgrade defcon

  # - git clone https://github.com/LettError/glyphNameFormatter.git
  # - cd glyphNameFormatter
  # - sudo -H python setup.py develop
  # - cd ..

  - pip install MutatorMath

  # - git clone https://github.com/typesupply/defcon.git
  # - cd defcon
  # - sudo -H python setup.py develop
  # - cd ..
  
  - sudo apt-get install -y shellcheck

  # proof
  - pip install brotli zopfli fontTools

script: 
  - "shellcheck $SHELL_PATH"
  - "sh $SHELL_PATH"
  - python make-webfonts.py


# deploy from master to gh-pages 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages #gh-pages is the default value




notifications:
  email: false
